"""Generate fonts.css: the five self-hosted faces, base64-inlined.

Keystamp ships as one file. Fonts used to come from Google over the
network, which meant a school hallway with bad wifi got fallback
letterforms for the first second of every page, and an offline device
got them permanently. These five faces are the product's voice, so they
are embedded: no request, no FOUT, no CDN.

Run after changing anything in assets/fonts/:
    python3 tools-build-fonts.py
"""
import base64, pathlib, struct

FACES = [
    # file,                          family,            weight, style
    ("CCWildWords-Roman.ttf",       "CC Wild Words",    "400",  "normal"),
    ("CCWildWords-Italic.ttf",      "CC Wild Words",    "400",  "italic"),
    ("CCWildWords-BoldItalic.ttf",  "CC Wild Words",    "700",  "italic"),
    ("JujutsuKaisen.ttf",           "Jujutsu Kaisen",   "400",  "normal"),
    ("BadaBoomBB.ttf",              "BadaBoom BB",      "400",  "normal"),
]

SRC = pathlib.Path("assets/fonts")

def family_of(p):
    """Read the name table so the CSS family can be checked against the file."""
    d = p.read_bytes()
    n = struct.unpack(">H", d[4:6])[0]
    tabs = {}
    for i in range(n):
        o = 12 + i * 16
        tag = d[o:o+4].decode("latin-1")
        off, ln = struct.unpack(">II", d[o+8:o+16])
        tabs[tag] = (off, ln)
    off, _ = tabs["name"]
    _, count, strOff = struct.unpack(">HHH", d[off:off+6])
    for i in range(count):
        rec = off + 6 + i * 12
        pid, eid, lid, nid, ln, o2 = struct.unpack(">HHHHHH", d[rec:rec+12])
        if nid != 1:
            continue
        raw = d[off+strOff+o2: off+strOff+o2+ln]
        try:
            txt = raw.decode("utf-16-be") if pid in (0, 3) else raw.decode("latin-1")
        except Exception:
            continue
        txt = txt.strip("\x00").strip()
        if txt:
            return txt
    return None

out = ['''/* ══════════════════════════════════════════════════════════════════
   THE THREE VOICES — self-hosted, embedded, no network

   Generated by tools-build-fonts.py from assets/fonts/. Do not edit by
   hand; edit the source files and regenerate.

   Jujutsu Kaisen  special display only — page titles, hero figures,
                   impact moments. A thin, wide face: it gives scale and
                   strangeness, never weight. Uppercase always, because
                   its lowercase e/o/u carry a diaeresis.
   BadaBoom BB     the header voice, and the only one of the three that
                   is actually heavy. Section titles, verbs, plate
                   headings — anything that has to read as a shout.
                   Unicase by way of alternate capitals: mixed-case
                   input yields varied caps, which is the point.
   CC Wild Words   everything a member reads, in three real faces.
                   Genuinely unicase: lowercase input draws capitals, so
                   all body copy sets in caps whether the CSS says so or
                   not. Keep sentences short for that reason.

   All are embedded as base64 rather than fetched. The app is one HTML
   file used on phones in a room with unreliable wifi; a webfont request
   there means a second of fallback letterforms on every load, and none
   at all offline. Embedding costs bytes once and removes the failure.

   COVERAGE WARNING, verified from the cmap tables, not assumed:
   no family maps U+00B7 MIDDLE DOT. CC Wild Words and BadaBoom BB also
   lack U+2014 EM DASH and U+2013 EN DASH, and BadaBoom lacks U+2026
   HORIZONTAL ELLIPSIS. Any of those in UI copy renders from a fallback
   face and visibly breaks the line. Use "/" as the separator and ";"
   where a sentence wants an em dash — all three families map both.
   ══════════════════════════════════════════════════════════════════ */
''']

for fn, fam, weight, style in FACES:
    p = SRC / fn
    actual = family_of(p)
    assert actual == fam, f"{fn}: name table says {actual!r}, css says {fam!r}"
    b64 = base64.b64encode(p.read_bytes()).decode("ascii")
    out.append(
        f"@font-face{{font-family:'{fam}';font-style:{style};font-weight:{weight};"
        f"font-display:block;"
        f"src:url(data:font/ttf;base64,{b64}) format('truetype')}}"
    )

pathlib.Path("fonts.css").write_text("\n".join(out) + "\n")
kb = pathlib.Path("fonts.css").stat().st_size / 1024
print(f"fonts.css written — {len(FACES)} faces, {kb:.0f} KB")
for fn, fam, w, s in FACES:
    print(f"   {fam:<16} {s:<7} {w}   <- {fn}")
